### ISSUE TITLE
[maigret] behance extracting wrong info

### ISSUE THREAD

**Issue by maximousblk** [soxoj/socid-extractor#78]
when using maigret the info extracted from behance.net is wrong. It's using info from liked posts.

expected:

key | value
-- | --
Uid | ???
First name | Maximous
Last name | Black
Username | maximousblk

actual:

key | value
-- | --
Uid | 3298983
First name | Nick
Last name | Buturishvili
Username | nikabuturishvili

images:
![image](https://user-images.githubusercontent.com/28438021/116855759-8d503000-ac17-11eb-9556-d842dda82644.png)

![image](https://user-images.githubusercontent.com/28438021/116876022-715d8600-ac39-11eb-83e5-4af9fef2b372.png)

**Comment by soxoj** [comment]
Fixed in #79, please check.

**Comment by maximousblk** [comment]
yes it works now
![image](https://user-images.githubusercontent.com/28438021/117052825-d1395700-ad35-11eb-9340-200738b7215a.png)

but it doesn't work with maigret yet

**Comment by soxoj** [comment]
It's okay, I will publish a new version.
