### ISSUE TITLE
Error / no results

### ISSUE THREAD

**Issue by tsmitsmitonline** [soxoj/socid-extractor#93]
I tested your application but I experience no results on URL's like:

twitter account URL
disqus account URL
facebook account URL

I see: analyzing URL ..... without result

**Comment by soxoj** [comment]
Hey, thank you for the feedback.
Can you please share a screenshot of results with `-d` option?

**Comment by tsmitsmitonline** [comment]
Examples: 

timo@TimoPOC:~$ socid_extractor --url https://twitter.com/WHInspector
Analyzing URL https://twitter.com/WHInspector...
timo@TimoPOC:~$ socid_extractor --url https://disqus.com/by/fitmakisun1972
Analyzing URL https://disqus.com/by/fitmakisun1972...

**Comment by soxoj** [comment]
Thank you, I've realized the problem. Will fix it in a few days.

**Comment by soxoj** [comment]
I fixed Twitter parsing: `socid_extractor --url 'https://twitter.com/WHInspector' --activation get_twitter_headers`
