### ISSUE TITLE
plase remove github autentication 

### ISSUE THREAD

**Issue by personic75** [soxoj/socid-extractor#97]
Hi Team

while downloading files it ask for git hub credentials please give alternatives as we cannot enter OTP in Linux

**Comment by soxoj** [comment]
Hey, what files are you trying to download?

**Comment by personic75** [comment]
pip3 install -U git+https://github.com/soxoj
It asking github credentials

**Comment by soxoj** [comment]
Please, try to run `pip3 install -U git+https://github.com/soxoj/socid_extractor`, it should not ask any credentials.

**Comment by personic75** [comment]
> Please, try to run `pip3 install -U git+https://github.com/soxoj/socid_extractor`, it should not ask any credentials.

 WARNING: The script socid_extractor is installed in '/home/kl/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by soxoj** [comment]
Looks like socid_extractor was successfully installed.
Do the following:
`export PATH=$PATH:/home/kl/.local/bin`
`socid_extractor --help`

**Comment by soxoj** [comment]
As far as I understand the problem was solved.
