### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by tsmitsmitonline** [soxoj/socid-extractor#99]
When I search: socid_extractor --url https://www.deviantart.com/muse190

I get no result:

:~$ socid_extractor --url https://www.deviantart.com/muse190
Analyzing URL https://www.deviantart.com/muse190...
:~$

**Comment by soxoj** [comment]
There is no such account. I suppose you have incorrectly copied the link from README: https://www.deviantart.com/muse1908. That account already exists and is correctly processed.
